#!/usr/bin/env bash
source ~/.bash_aliases

vs() {
	cd testserver
	./start.sh > server.log &
	sleep 1
	cd ..
	./testclient $1 $2 100 > battles/$1-$2
	killJava
	sleep 1
}

vs 1.6.0 1.6.1
vs 1.6.0 1.7.0
vs 1.6.0 1.8.0
vs 1.6.1 1.7.0
vs 1.6.1 1.8.0
vs 1.7.0 1.8.0
vs 1.6.0 2.0.0
vs 1.7.0 2.0.0
vs 1.8.0 2.0.0
